### ISSUE TITLE
Help required

### ISSUE THREAD

**Issue by Orneyfish** [chambliss/Multilingual_NER#18]
Does this model take custom tags? I want to train my model for some custom tags for my entitites.

**Comment by chambliss** [comment]
Yes it does! Simply change the label types you want to support in [config/config.yaml](https://github.com/chambliss/Multilingual_NER/blob/master/config/config.yml).

**Comment by Orneyfish** [comment]
Do I need to tag my custom data or BERT can do it? Like I want to add some
medical terms so I need to tag my data?

**Comment by chambliss** [comment]
Yes, you will need to tag your own data. BERT has no way of tagging it for you, unfortunately. If only the models were that smart :) 

If you are looking for something quick to get started with annotating as a single user, I would recommend [LabelStudio](https://github.com/heartexlabs/label-studio). You can spin up your labeling instance as a local web app using your own documents, and be off to the races.

**Comment by Orneyfish** [comment]
Thanks for your reply. That's a good help :)
